from pathlib import Path


# 这里统一放整个子项目用到的路径和常量配置。
# 后面如果目录结构变化，只需要改这一处。
APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent

CONFIG_DIR = PROJECT_ROOT / "config"
DOTENV_PATH = CONFIG_DIR / ".env"

MODEL_DIR = PROJECT_ROOT / "model"
EMBEDDING_MODEL_PATH = MODEL_DIR / "bge-base-zh-v1.5"

VECTORSTORE_DIR = PROJECT_ROOT / "vectorstore_rag"

DATA_DIR = APP_DIR / "data"
# 这里提前创建 data 目录，避免后面写会话历史时因为目录不存在报错。
DATA_DIR.mkdir(exist_ok=True)
HISTORY_PATH = DATA_DIR / "conversation_history.json"

NEO4J_HOME = PROJECT_ROOT / "neo4j_kg_db"
NEO4J_JAVA_HOME = (
    Path.home()
    / ".Neo4jDesktop2"
    / "Cache"
    / "runtime"
    / "zulu21.44.17-ca-jdk21.0.8-win_x64"
)
NEO4J_BOLT_URL = "bolt://127.0.0.1:8687"
NEO4J_HTTP_URL = "http://127.0.0.1:8474"
NEO4J_START_SCRIPT = NEO4J_HOME / "start_kg_db.bat"
NEO4J_STOP_SCRIPT = NEO4J_HOME / "stop_kg_db.bat"

# 这些常量用来控制检索规模，避免一次取回太多结果把上下文塞满。
VECTOR_TOP_K = 6
GRAPH_KEYWORD_LIMIT = 3
GRAPH_RESULT_LIMIT = 8
FINAL_EVIDENCE_LIMIT = 10
FINAL_SOURCE_LIMIT = 6
MIN_VERIFICATION_CONFIDENCE = 0.55
QUERY_EXPANSION_ENABLED = True
QUERY_EXPANSION_NUM = 3
HYDE_ENABLED = False
PER_QUERY_VECTOR_TOP_K = 4
PER_QUERY_GRAPH_LIMIT = 4
SESSION_SUMMARY_PATH = DATA_DIR / "session_summaries.json"
LONG_TERM_MEMORY_PATH = DATA_DIR / "long_term_memory.json"
MEMORY_SUMMARY_TURNS = 12
MEMORY_SUMMARY_TOPIC_LIMIT = 6
LONG_TERM_MEMORY_TOP_K = 4
LONG_TERM_MEMORY_LIMIT = 120
LONG_TERM_MEMORY_TTL_DAYS = 180
LONG_TERM_MEMORY_MIN_CONFIDENCE = 0.6
LONG_TERM_MEMORY_MIN_SCORE = 0.35
LONG_TERM_MEMORY_WRITE_CONFIDENCE = 0.75
LONG_TERM_MEMORY_WRITE_IMPORTANCE = 0.6
SUMMARY_UPDATE_EVERY_N_TURNS = 5
SUMMARY_MAX_HISTORY_CHARS = 3000
SUMMARY_MAX_CHARS = 1200
AGENT_WORKFLOW_ENABLED = True
AGENT_WORKFLOW_BACKEND = "python"
PLANNER_ENABLED = False
REFLECTION_MAX_RETRIES = 1
REFLECTION_RETRIEVAL_RETRY_ENABLED = False
INCLUDE_AGENT_TRACE = False
RETRIEVAL_PARALLEL_ENABLED = True
RETRIEVAL_MAX_WORKERS = 6
RETRIEVAL_TASK_TIMEOUT_SECONDS = 20
RETRIEVAL_CACHE_ENABLED = True
RETRIEVAL_CACHE_TTL_SECONDS = 300
RETRIEVAL_CACHE_MAX_ITEMS = 256
